[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["postrv <71533421+postrv@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
image = "0.13.0"